# config-repo/order-service.yml
spring:
  application:
    name: order-service
  data:
    mongodb:
      # uri: mongodb://localhost:27017/ordersdb
      uri: mongodb://mongodb:27017/orderDb
  cloud:
    config:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50


