# config-repo/order-service.yml
spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/orderDb

  cloud:
    config:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
