# config-repo/user-service.yml
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/usersdb
  cloud:
    config:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
